language: python
branches:
  only:
    - master
python:
  - 3.6
install:
  pip install -r requirements.txt
script:
  - python manage.py test
after_script
  if: branch = master
  - curl -X POST https://registry.hub.docker.com/u/code4clouds/azure_visualizer/trigger/$dockerhub_trigger/
